site_name: Juan Lara
site_description: Portfolio website for Juan Lara
site_url: https://juanlara.io
repo_url: https://github.com/idfx/idfx.github.io
copyright: Copyright &copy; 2015 - 2025 Juan Lara

plugins:
  - search
  - blog:
      blog_toc: true
      pagination_per_page: 5
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - tags:
      tags_file: blog/tags.md
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      skip_classes:
        - custom-skip-class-name
      auto_caption: true
      caption_position: bottom
      background: white
      shadow: true
      manual: false

nav:
  - Home: index.md
  - Projects:
      - blog/index.md
      - Tags: blog/tags.md
  - Contact: contact.md

theme:
  name: material
  logo: images/cropped-logo-large-white.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/x-twitter
      name: Me on X
      link: https://x.com/j1lara
    - icon: fontawesome/brands/github
      name: Me on Github
      link: https://github.com/idfx
    - icon: /fontawesome/regular/envelope
      name: Send me an email
      link: mailto:juandariolara@gmail.com
    - icon: fontawesome/brands/linkedin
      name: Me on LinkedIn
      link: www.linkedin.com/in/j1lara
