authors:
  craigdarroch:
    name: Craigdarroch Castle
    description: Victoria, BC
    avatar: /images/logos/crg.jpg
  telus:
    name: Telus World of Science Edmonton
    description: Edmonton, AB
    avatar: /images/logos/TELUS+logo.png
  cdm:
    name: Centre for Digital Media
    description: Vancouver, BC
    avatar: /images/logos/cdm.jpg
  autodesk:
    name: Autodesk
    description: San Francisco, CA
    avatar: https://brand.autodesk.com/app/uploads/2021/04/symbol-1.svg
  discovery:
    name: Discovery Centre
    description: Halifax, NS
    avatar: /images/logos/discoverycentre.jpg
  scienceworld:
    name: Science World
    description: Vancouver, BC
    avatar: /images/logos/scienceworld.png
  perlan:
    name: Perlan Museum
    description: Reykjavik, Iceland
    avatar: /images/logos/perlan.png
  biosphere:
    name: Biosphere, Space for Life
    description: Montreal, QC
    avatar: /images/logos/biosphere.jpeg
  ngx:
    name: NGX Interactive
    description: Vancouver, BC
    avatar: /images/logos/ngx.jpeg
